apiVersion: v1
# Kind for kubernets ConfigMap
kind: ConfigMap
metadata:
  # Name your ConfigMap
  name: db-secret-credentials
  labels:
    app: postgresdb
data:
  # User DB
  POSTGRES_DB: testDB
  # Db user
  POSTGRES_USER: testUser
  # Db password
  POSTGRES_PASSWORD: testPassword
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config
data:
  init.sql: |
    -- Create a database
    CREATE DATABASE productdb2;
    -- Switch to the new database
    \c mydatabase;
    -- Create a table
    CREATE TABLE sample_table (
        id SERIAL PRIMARY KEY,
        name TEXT
    );
    -- Insert some data
    INSERT INTO sample_table (name) VALUES ('data1'), ('data2');  