apiVersion: v1
kind: ConfigMap
metadata:
  name: order-serivce-config
  labels:
    data: config
data:
  host: "NOTSET"
---

apiVersion: v1
kind: Secret
metadata:
  name: order-serivce-secret
  labels:
    data: ordsvc-secret
type: Opaque
data:
  postgresdb_cn: "SG9zdD1wb3N0Z3Jlc2RiLmRlZmF1bHQuc3ZjLmNsdXN0ZXIubG9jYWw7UG9ydD01NDMyO0RhdGFiYXNlPXByb2R1Y3RkYjtVc2VybmFtZT10ZXN0VXNlcjtQYXNzd29yZD10ZXN0UGFzc3dvcmQ="
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-serivce-deployment
spec:
  selector:
    matchLabels:
      app: order-serivce-pod
  template:
    metadata:
      labels:
        app: order-serivce-pod
    spec:
      containers:
      - name: order-serivce-container
        image: yaseralissa/order-service:latest
        imagePullPolicy: Always #Never
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
        env:
        - name: DB_ConnectionString
          valueFrom:
            secretKeyRef: 
              name: order-serivce-secret
              key: postgresdb_cn
        - name: DB_Host
          valueFrom:
            configMapKeyRef:
              name: order-serivce-config
              key: host
